deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: "filesystem"
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  # Enable retention and compaction
  limits_config:
    retention_period: 168h # Retain logs for 7 days
  compactor:
    working_directory: /var/loki/compactor
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 30
    delete_request_store: filesystem

# Disable the components associated with Simple Scalable mode
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 64Gi
