grafana:
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: true
    type: pvc
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 5Gi
  ingress:
    enabled: true
    hosts:
      - grafana.sotongpt.soton.ac.uk
    path: /
    pathType: Prefix
    ingressClassName: traefik
    tls:
        - secretName: srv04885-tls
          hosts:
            - grafana.sotongpt.soton.ac.uk
  service:
    type: ClusterIP
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false
prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    nodeSelector:
      kubernetes.io/hostname: srv04885
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 128Gi
alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
prometheus-node-exporter:
  hostNetwork: false
  hostPID: true
  service:
    port: 9100
    targetPort: 9100
