apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-cnpg
  namespace: monitoring 
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      cnpg.io/cluster: postgres-cnpg
  podMetricsEndpoints:
  - port: metrics
